"use client";
import dynamic from "next/dynamic";
import "./globals.css";
import { Inter, Roboto, Roboto_Condensed } from "next/font/google";
// import "./index.css";
import "../app/components/css/header.css";
import "../app/components/css/home.css";

import "../app/components/css/about.css";
import "../app/components/css/project.css";
import "../app/components/css/contact.css";
import "../app/components/css/service.css";
import "react-toastify/dist/ReactToastify.css";
import Head from "next/head";
import css from "styled-jsx/css";

const fontStyles = css`
  @import url("https://fonts.googleapis.com/css2?family=Roboto+Condensed:wght@300&display=swap");

  body {
    font-family: "Roboto Condensed", sans-serif;
    font-weight: 300;
  }
`;
const ToastContainer = dynamic(
  () => import("react-toastify").then((module) => module.ToastContainer),
  {
    ssr: false,
  }
);

const inter = Inter({ subsets: ["latin"] });
const roboto = Roboto_Condensed({ subsets: ["cyrillic"], weight: "700" });

// export const metadata = {
// 	title: "Create Next App",
// 	description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <title>Prem Pachabhaiya</title>
      <Head>
        <link
          href="https://fonts.googleapis.com/css2?family=Roboto+Condensed:wght@300&display=swap"
          rel="stylesheet"
        />
      </Head>
      <body>
        <style jsx>{fontStyles}</style>
        {children}
        <ToastContainer
          position="top-center"
          autoClose={2500}
          className="toast-container"
        />
      </body>
    </html>
  );
}
